spring:
  application:
    name: gateway
#路由转发
  cloud:
    gateway:
      routes[0]:
        id: system
        uri: http://127.0.0.1:9001
        predicates[0]:
          name: Path
          args[0]: /system/**
#添加一个路由转发 所有带business都转发到9002中去
      routes[1]:
        id: business
        uri: http://127.0.0.1:9002
        predicates[0]:
          name: Path
          args[0]: /business/**

server:
  port: 9000
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/