spring:
  application:
    name: system
#配置数据库连接
  datasource:
    url: jdbc:mysql://localhost:3306/course?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: course
    password: course
    driver-class-name: com.mysql.jdbc.Driver
server:
  port: 9001
  servlet:
    context-path: /system
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
#mapper的路径
mybatis:
  mapper-locations: classpath:/mapper/*.xml
